baseURL = 'https://kcdavidson.net/'
title = 'k.c. davidson'
author = "k.c. davidson"
languageCode = 'en-us'
defaultContentLanguage = 'en'
theme = 'paper'
paginate = 3
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
# ------------------------------

[params]
  color = 'linen'
  monoDarkIcon = true
# twitter = 'nanxiaobei'
# github = 'nanxiaobei'
# instagram = 'nan.xiaobei'

# avatar = 'nanxiaobei@gmail.com'
  name = 'kc davidson'
# bio = 'Discover fresh context'
# ------------------------------

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
[markup.highlight]
  lineNos = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true