baseURL = "https://kcdavidson.net/"
homepage = "https://kcdavidson.net/"
title = "k.c. davidson"
author = "k.c. davidson"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "paper"
paginate = 10
enableInlineShortcodes = true
disablePostNavigation = false
ignoreErrors = ["error-remote-getjson"]
# ------------------------------
[permalinks]
  posts = "/:year/:month/:day/:slug/"
  pages = "/:slug/"
  sections = "/:slug/"
  aliases = "/:slug/"
# ------------------------------
[params]
  color = "linen"
  monoDarkIcon = true
  name = "k.c. davidson"
  bio = "This is my bio."
  twitter = "kkkkkcccccddddd"
  instagram = "kkkkkcccccddddd"
# github = "nanxiaobei"
# avatar = "nanxiaobei@gmail.com"
# ------------------------------
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
# ------------------------------
[frontmatter]
  date = ["date", "pubdate", "publishDate", "lastmod"]
  pubdate = ["pubdate", "publishDate", "date", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]
# ------------------------------
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    lineNos = true
# ------------------------------
[menu]
  [[menu.main]]
    identifier = "home"
    slug = "/"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    slug = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "archive"
    slug = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    slug = "about"
    name = "About"
    url = "/about/"
    weight = 40
  [[menu.main]]
    identifier = "contact"
    slug = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50
# ------------------------------
# [privacy]
#   [privacy.vimeo]
#     disabled = false
#     simple = true
#   [privacy.twitter]
#     disabled = false
#     enableDNT = true
#     simple = true
#   [privacy.instagram]
#     disabled = false
#     simple = true
#   [privacy.youtube]
#     disabled = false
#     privacyEnhanced = true
# ------------------------------
[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true