baseURL = "https://kcdavidson.net/"
title = "kcdavidson.net"
author = "k.c. davidson"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "paper"
paginate = 10
# ------------------------------
[permalinks]
  posts = "/:year/:month/:day/:slug/"
  pages = "/:slug/"
  sections = "/:slug/"
  aliases = "/:slug/"
# ------------------------------
[params]
  color = "linen"
  monoDarkIcon = true
  name = "k.c. davidson"
  bio = "This is my bio."
  twitter = "kkkkkcccccddddd"
  instagram = "kkkkkcccccddddd"
  github = "kcdavidson"
  rss = true
  disablePostNavigation = false
# avatar = "nanxiaobei@gmail.com"
# ------------------------------
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
# ------------------------------
[frontmatter]
  date = ["date", "pubdate", "publishDate", "lastmod"]
  pubdate = ["pubdate", "publishDate", "date", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]
# ------------------------------
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = true
# ------------------------------
[menu]
  [[menu.main]]
    identifier = "posts"
    slug = "post"
    name = "Posts"
    url = "/post/"
    weight = 20
  [[menu.main]]
    identifier = "archive"
    slug = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    slug = "about"
    name = "About"
    url = "/about/"
    weight = 40
  [[menu.main]]
    identifier = "contact"
    slug = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50
# ------------------------------
# [privacy]
#   [privacy.vimeo]
#     disabled = false
#     simple = true
#   [privacy.twitter]
#     disabled = false
#     enableDNT = true
#     simple = true
#   [privacy.instagram]
#     disabled = false
#     simple = true
#   [privacy.youtube]
#     disabled = false
#     privacyEnhanced = true
# ------------------------------
[services]
  [services.instagram]
    disableInlineCSS = false
  [services.twitter]
    disableInlineCSS = false
[security]
  enableInlineShortcodes = true
[misc]
  ignoreErrors = ["error-remote-getjson"]
