baseURL = 'https://kcdavidson.net/'
languageCode = 'en-us'
title = 'kcdavidson.net'
theme = 'kcd-hugo-theme'

# [[menu.main]]
# name = 'Home'
# pageRef = '/'
# weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menu.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

# [[menu.social]]
#   name = 'RSS Feed'
#   pre = "rss"
#   url = "/index.xml"
#   weight = 10

[services]
  [services.googleAnalytics]
    ID = 'G-3ZS2PC83EX'

  [services.disqus]
    shortname = 'kcdavidson'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"

[outputs]
  home = ["HTML", "RSS"]