baseURL = 'https://kcdavidson.net/'
languageCode = 'en-us'
title = 'kcdavidson.net'
theme = 'kcd-hugo-theme'

# [[menus.main]]
# name = 'Home'
# pageRef = '/'
# weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[services]
  [services.disqus]
    shortname = 'kcdavidson'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
